# Generated by Django 5.2.4 on 2025-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0002_eventcreate_eventdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcreate",
            name="EventDescription",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="eventcreate",
            name="EventName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="eventcreate",
            name="EventVenue",
            field=models.CharField(max_length=30),
        ),
    ]
