# Generated by Django 5.2.1 on 2025-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.TextField(max_length=30)),
                ('EventDescription', models.TextField(max_length=100)),
                ('EventVenue', models.TextField(max_length=30)),
            ],
        ),
    ]
