# Generated by Django 5.2.1 on 2025-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcreate',
            name='EventDate',
            field=models.DateField(default='2025-07-20'),
        ),
    ]
